version: '2.4'

x-common: &common
  extends:
    file: base.yml
    service: prod

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  broker:
    image: confluentinc/cp-kafka:6.1.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0

  stream_reader:
    <<: *common
    depends_on:
      - broker
      - classification
      - ch_consumer
    volumes:
      - ../data/internal/:/data/internal/

    entrypoint:
      bash -c "echo 'Giving Kafka a bit of time to start up…' &&
      sleep 30 &&
      python3 ./bigdata_itmo/stream_reader/create_topics.py &&
      sleep 10 &&
      python3 ./bigdata_itmo/stream_reader/stream_reader.py"

  classification:
    <<: *common
    depends_on:
      - broker
    volumes:
      - ../data/internal/:/data/internal/
    entrypoint:
      bash -c "echo 'Giving Kafka a bit of time to start up…' &&
      sleep 50 &&
      python3 ./bigdata_itmo/news_classifier/run_network.py"

  ch_consumer:
    <<: *common
    depends_on:
      - broker
    volumes:
      - /tmp/bd_itmo/:/bd_itmo/
    entrypoint:
      bash -c "echo 'Giving Kafka a bit of time to start up…' &&
      sleep 50 &&
      python3 ./bigdata_itmo/clickhouse/run_consumer.py"

  clickhouse:
    image: yandex/clickhouse-server
    hostname: clickhouse
    container_name: clickhouse
    depends_on:
      - ch_consumer
    ports:
    - 8123
    volumes:
      - ../clickhouse_init/:/docker-entrypoint-initdb.d/

  grafana-storage:
    image: busybox:latest
    container_name: grafana-storage
    depends_on:
      - clickhouse
    volumes:
      - /var/lib/grafana

  grafana:
    image: qxip/clickhouse-grafana
    container_name: grafana
    depends_on:
      - clickhouse
    ports:
     - "3000:3000"
    volumes_from:
      - grafana-storage
    environment:
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,vertamedia-clickhouse-datasource"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
